package ud04_02Departamentos.entity;
// Generated 22 ene 2025 11:03:48 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departamentos generated by hbm2java
 */
@Entity
@Table(name = "departamentos", catalog = "ejemplo")
public class Departamentos implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@Column(name = "dept_NO", unique = true, nullable = false)
	private int deptNo;
	@Column(name = "dnombre", length = 15)
	private String dnombre;
	private String loc;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departamentos")
	private Set <Empleados> empleados = new HashSet<Empleados>(0);


	public Departamentos() {
	}

	public Departamentos(int deptNo) {
		this.deptNo = deptNo;
	}

	public Departamentos(int deptNo, String dnombre, String loc, Set<Empleados> empleados) {
		this.deptNo = deptNo;
		this.dnombre = dnombre;
		this.loc = loc;
		this.empleados = empleados;
	}


	public int getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(int deptNo) {
		this.deptNo = deptNo;
	}

	public String getDnombre() {
		return this.dnombre;
	}

	public void setDnombre(String dnombre) {
		this.dnombre = dnombre;
	}

	@Column(name = "loc", length = 15)
	public String getLoc() {
		return this.loc;
	}

	public void setLoc(String loc) {
		this.loc = loc;
	}

	public Set<Empleados> getempleados() {
		return this.empleados;
	}

	public void setempleados(Set<Empleados> empleados) {
		this.empleados = empleados;
	}

}
