package ud04_02Departamentos.entity;
// Generated 22 ene 2025 11:03:48 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Empleados generated by hbm2java
 */
@Entity
@Table(name = "empleados", catalog = "ejemplo")
public class Empleados implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@Column(name = "Emp_no", unique = true, nullable = false)
	private int empNo;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dept_NO")
	private Departamentos departamentos;
	@Column(name = "apellido", length = 20)
	private String apellido;
	@Column(name = "oficio", length = 15)
	private String oficio;
	@Column(name = "dir")
	private Integer dir;
	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_alta", length = 10)
	private Date fechaAlta;
	@Column(name = "salario", precision = 6)
	private Float salario;
	@Column(name = "comision", precision = 6)
	private Float comision;

	public Empleados() {
	}

	public Empleados(int empNo) {
		this.empNo = empNo;
	}

	public Empleados(int empNo, Departamentos departamentos, String apellido, String oficio, Integer dir,
			Date fechaAlta, Float salario, Float comision) {
		this.empNo = empNo;
		this.departamentos = departamentos;
		this.apellido = apellido;
		this.oficio = oficio;
		this.dir = dir;
		this.fechaAlta = fechaAlta;
		this.salario = salario;
		this.comision = comision;
	}


	public int getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(int empNo) {
		this.empNo = empNo;
	}


	public Departamentos getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Departamentos departamentos) {
		this.departamentos = departamentos;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getOficio() {
		return this.oficio;
	}

	public void setOficio(String oficio) {
		this.oficio = oficio;
	}

	public Integer getDir() {
		return this.dir;
	}

	public void setDir(Integer dir) {
		this.dir = dir;
	}


	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Float getSalario() {
		return this.salario;
	}

	public void setSalario(Float salario) {
		this.salario = salario;
	}

	public Float getComision() {
		return this.comision;
	}

	public void setComision(Float comision) {
		this.comision = comision;
	}

}
